name: Starting-AWS-Infrastructure
env:
  AWS_DEFAULT_REGION: eu-central-1
  TF_VAR_backend_s3_bucket: mandor-wordpress-bucket
  TF_VAR_backend_s3_region: eu-central-1


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  terraform:
    name: 'terraform'  
    runs-on: ubuntu-latest
    
defaults:
  run:
    shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Terraform Init
      env: production
      run:  
        terraform init -input=false
    
    - name: Terraform Plan
      run: terraform plan -input=false
      
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
                
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-access-secret-key-id: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
