env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
TF_VAR_project_name: ${{ github.event.inputs.TF_VAR_project_name }}
TF_VAR_env_name: ${{ github.event.inputs.TF_VAR_env_name }}
TF_VAR_backend_s3_bucket: mandor-wordpress-bucket
TF_VAR_backend_s3_region: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
build-infra:
name: 'Build infra'
runs-on: terraform-servers.tf

steps:
- name: 'Checkout the code'
 uses: actions/checkout@v2
 
- name: Configure .env
run: |
cp .env.ci.template .env

- name: Construct infrasctructure
 - name: Clean up
 if: ${{ always() }}
 run: |
 rm -vrf *
